
name: Node CI with AdonisJS

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "HOST=${{ secrets.HOST }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "APP_NAME=${{ secrets.APP_NAME }}" >> .env
          echo "DRIVE_DISK=${{ secrets.DRIVE_DISK }}" >> .env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
          echo "MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }}" >> .env
          echo "MISTRAL_API_URL=${{ secrets.MISTRAL_API_URL }}" >> .env
          echo "MISTRAL_MODEL=${{ secrets.MISTRAL_MODEL }}" >> .env

      - name: Build project
        run: node ace build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: k33ngtomide/chatbot

